# config/_default/languages.zh-cn.toml

baseURL = "https://sunweiwe.github.io/"
languageCode = "en-us"
title = "sunweiwe/blog"
theme = 'congo'

defaultContentLanguage = 'zh-cn'
autoSwitchAppearance = true
locale = true
enableCodeCopy = true
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[author]
  name = "sunweiwe"
  headline = "A generally awesome human"


[params]
  description = "关于代码，关于生活."
  dateFormat = "02.01.2006"

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/sunweiwe"
    weight = 4

[footer]
  showAppearanceSwitcher = true