baseURL = "https://sunweiwe.github.io/"
languageCode = "en-us"
title = "sunweiwe/blog"
theme = 'hugo-book'

disablePathToLower = true
enableGitInfo = true


[params]
  subtitle = "关于代码，关于生活."
  dateFmt = "02.01.2006"
   
  BookTheme = 'dark'

  BookToC = true

  BookMenuBundle = '/menu'

  BookSearch = true

  BookDateFormat = 'January 2, 2006'

  BookComments = true

  BookPortableLinks = true
  
  BookServiceWorker = true

  mathjax = true  # not required

  showAllPostsArchive = true

  rss = true

  [[comments]]
    enabled = true
  
[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/sunweiwe"
    weight = 4


[markup]
  [markup.goldmark.renderer]
    unsafe = true
  
  [markup.tableOfContents]
    startLevel = 1

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
