baseURL = "https://sunweiwe.github.io/"
languageCode = "en-us"
title = "sunweiwe/blog"
theme = "cactus"


[params]
  subtitle = "关于代码，关于生活."
  dateFmt = "02.01.2006"
  
  customCSS = true
  mainSection = "posts"
  mainSectionTitle = "Blog"
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
  tocInline = true

  mathjax = true  # not required

  showAllPostsArchive = true

  rss = true

  [[comments]]
    enabled = true
  
[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/sunweiwe"
    weight = 4


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
