baseURL = "https://sunweiwe.github.io/"
languageCode = "en-us"
title = "sunweiwe/blog"
theme = 'congo'

defaultContentLanguage = 'zh-cn'
autoSwitchAppearance = true


[article]
  showTaxonomies = true
  showSummary = true

# config/_default/languages.en.toml

title = "My awesome website"

[author]
  name = "sunweiwe"
  headline = "A generally awesome human"

locale = false


[params]
  description = "关于代码，关于生活."
  dateFormat = "02.01.2006"

[header]
  
  
[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/sunweiwe"
    weight = 4


[markup]
  [markup.goldmark.renderer]
    unsafe = true
  
  [markup.tableOfContents]
    startLevel = 1

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
